apiVersion: 1

datasources:
  - name: elasticsearch-v7
    type: elasticsearch
    access: proxy
    database: "twitter-streaming-api"
    url: http://localhost:9200
    jsonData:
      timeInterval: "10s"
      interval:
      timeField: "@timestamp"
      esVersion: 70
      logMessageField: message
